# Docker Compose for LottoDrop Frontend
# Production-ready configuration

version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:3001}
        - VITE_WS_URL=${VITE_WS_URL:-ws://localhost:3001}
        - VITE_SENTRY_DSN=${VITE_SENTRY_DSN:-}
        - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
    ports:
      - "${FRONTEND_PORT:-8080}:8080"
    environment:
      - NODE_ENV=production
    networks:
      - lottodrop-network
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Security
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /var/cache/nginx:uid=1001,gid=1001
      - /var/run:uid=1001,gid=1001
      - /tmp:uid=1001,gid=1001
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Logging
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  lottodrop-network:
    external: true